---
- name: Deploy to droplet
  hosts: div.is
  remote_user: root
  tasks:
    - name: Install Podman
      command: dnf install podman -y
    - name: Copy back end files
      synchronize:
        src: .
        dest: /usr/src/
        mode: push
        rsync_opts:
          - "--exclude=client/target"
          - "--exclude=client/node_modules"
          - "--exclude=wiki"
          - "--exclude=yew/target"
          - "--exclude=yew/node_modules"
          - "--exclude=yew/.cache"
          - "--exclude=.git"
      run_once: true
    - name: Clean images
      command: sudo podman image rm --all --force
    - name: Clean containers
      command: sudo podman container rm --all --force
    - name: Build backend image
      command: sudo podman build /usr/src/div/back -t divb
    - name: Build frontend image
      command: sudo podman build /usr/src/div/client -f Dockerfile.prod -t divf
    - name: Run backend image
      command: sudo podman run -dt -p 3001:3001 localhost/divb
    - name: Run frontend image
      command: sudo podman run -dt -p 80:5005 localhost/divf

# to add: build, run postgres db
# to add: build, run redis
# to add: build, run ip networking w/ api.div.is or something
# to add: build, run yew website
# to add: second host droplet
# to add: create pod + networking
