---
- name: Deploy to droplet
  hosts: div.is
  remote_user: root
  tasks:
    - name: Install Podman
      command: dnf install podman -y
    - name: Create install directory
      file:
        state: directory
        path: /usr/src/
    - name: Copy back end files
      synchronize:
        src: .
        dest: /usr/src/
        rsync_opts:
          - "--exclude=client/target"
          - "--exclude=client/node_modules"
          - "--exclude=wiki"
          - "--exclude=yew/target"
          - "--exclude=yew/node_modules"
    - name: Create podman pod
      command: sudo podman pod create -p 80 -p 5432 -p 3001 --name divis
    - name: Build backend image
      command: sudo podman build /usr/src/div/back -t divb
    - name: Build frontend image
      command: sudo podman build /usr/src/div/client -t divf
    - name: Run backend image
      command: sudo podman run -dt --pod divis 3001:3001 localhost/divb
    - name: Run frontend image
      command: sudo podman run -dt --pod divis 80:5005 localhost/divf

# to add: build, run postgres db
# to add: build, run redis
# to add: build, run ip networking w/ api.div.is or something
# to add: build, run yew website
# to add: second host droplet
# to add: create pod + networking
