---
- name: Deploy to droplet
  hosts: div.is
  remote_user: root
  tasks:
    - name: Install Podman
      command: dnf install podman -y
    - name: Copy back end files
      synchronize:
        src: .
        dest: /usr/src/
        mode: push
        rsync_opts:
          - "--exclude=client/target"
          - "--exclude=client/node_modules"
          - "--exclude=wiki"
          - "--exclude=yew/target"
          - "--exclude=yew/node_modules"
          - "--exclude=yew/.cache"
          - "--exclude=.git"
      run_once: true
    - name: Remove existing containers
      command: sudo ./pod.sh down
    - name: Start production containers
      command: sudo ./pod.sh up prod

# to add: build, run postgres db
# to add: build, run redis
# to add: build, run ip networking w/ api.div.is or something
# to add: build, run yew website
# to add: second host droplet
# to add: create pod + networking
