version: '4'
services:
  api:
    build: ./src
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=api"
      - "traefik.rule=Host:api.pecu.cc"
      - "traefik.port=80"
    networks:
      - "traefik_default"
    restart: always
  front:
    build: ./client
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=front"
      - "traefik.rule=Host:pecu.cc"
      - "traefik.port=80"
    networks:
      - "traefik_default"
    restart: always
  web:
    build: ./nginx
    volumes:
      - ./site.template: /etc/nginx/config.d/site.template
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=pecu.cc
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


networks:
  traefik_default:
    external:
      name: traefik_default
