version: '4'
services:
  front:
    build: ./front
    volumes:
      - ./web:/usr/src/app
    ports:
      - "3000:3000"
    comand: bash -c "yarn && yarn start"

  back:
    build: ./back
    ports:
      - "3001:3001"
    volumes:
      - ./back:/usr/src/app
    links:
      - db

  db:
    image: "postgres:13-alpine"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: {}

networks:
  traefik_default:
    external:
      name: traefik_default
