FROM rust:latest-slim

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

RUN apt-get update && apt-get install nodejs

RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

WORKDIR /usr/src/div

COPY . .

RUN npm install

EXPOSE 8000

CMD [ "npm", "start" ]
