FROM postgres:13-alpine

RUN mkdir /var/lib/postgres

WORKDIR /var/lib/postgres

EXPOSE 5432

#VOLUME ["/var/lib/postgresql/data"]

#VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

