---
- name: Deploy to div.is
  hosts: div.is
  remote_user: root
  vars:
    api_url: default
    host_front_port: 80
    cont_front_port: 5005
    host_back_port: 3001
    cont_back_port: 3001
  tasks:
    - name: Install Podman
      dnf:
        name:
          - podman
        state: latest
    - name: Copy back end files
      synchronize:
        src: client
        dest: /usr/src/div/
        mode: push
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=scripts"
      run_once: true
    - name: Clean images
      command: sudo podman image rm --all --force
    - name: Clean containers
      command: sudo podman container rm --all --force
    - name: Build frontend image
      command: sudo podman build /usr/src/div/client -f Dockerfile.prod -t divfprod
    - name: Run frontend image
      command: sudo podman run --rm -dt -p 80:5005 --name divfprod localhost/divfprod

# to add: build, run postgres db
# to add: build, run redis
# to add: build, run ip networking w/ api.div.is or something
# to add: build, run yew website
# to add: second host droplet
# to add: create pod + networking
